HSEARCH-4313 Upgrade to asciidoctor-maven-plugin 2.2.1, asciidoctorj 2.5.2
Mainly to get a bugfix regarding additional section IDs
(https://docs.asciidoctor.org/asciidoc/latest/sections/custom-ids/#assign-additional-ids).
The previous versions of AsciiDoctor used to embed those additional IDs
as anchors (<a id="...>) when rendering *links* to the sections, which
resulted in multiple anchors with the same ID and made the whole concept
of additional section IDs completely useless.

Note that upgrading to asciidoctorj-pdf 1.5.0 or later won't work for
some reason; we're getting strange errors that led me to think the
font-size has the wrong type (string instead of number):

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to
execute goal
org.asciidoctor:asciidoctor-maven-plugin:2.2.1:process-asciidoc
(reference-output-pdf) on project hibernate-search-documentation:
Execution reference-output-pdf of goal
org.asciidoctor:asciidoctor-maven-plugin:2.2.1:process-asciidoc failed:
org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `-'
for #<String:0x31a89b54>
Did you mean?  -@
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:148)
    at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject
(LifecycleModuleBuilder.java:117)
    at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject
(LifecycleModuleBuilder.java:81)
    at
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build
(SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute
(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native
Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced
(Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch
(Launcher.java:225)
    at
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode
(Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main
(Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution
reference-output-pdf of goal
org.asciidoctor:asciidoctor-maven-plugin:2.2.1:process-asciidoc failed:
org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `-'
for #<String:0x31a89b54>
Did you mean?  -@
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo
(DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:148)
    at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject
(LifecycleModuleBuilder.java:117)
    at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject
(LifecycleModuleBuilder.java:81)
    at
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build
(SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute
(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native
Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced
(Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch
(Launcher.java:225)
    at
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode
(Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main
(Launcher.java:347)
Caused by: org.asciidoctor.jruby.internal.AsciidoctorCoreException:
org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `-'
for #<String:0x31a89b54>
Did you mean?  -@
    at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile
(JRubyAsciidoctor.java:402)
    at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convertFile
(JRubyAsciidoctor.java:368)
    at org.asciidoctor.maven.AsciidoctorMojo.convertFile
(AsciidoctorMojo.java:451)
    at org.asciidoctor.maven.AsciidoctorMojo.processSources
(AsciidoctorMojo.java:250)
    at org.asciidoctor.maven.AsciidoctorMojo.processAllSources
(AsciidoctorMojo.java:166)
    at org.asciidoctor.maven.AsciidoctorMojo.execute
(AsciidoctorMojo.java:156)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo
(DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute
(MojoExecutor.java:148)
    at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject
(LifecycleModuleBuilder.java:117)
    at
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject
(LifecycleModuleBuilder.java:81)
    at
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build
(SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute
(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native
Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced
(Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch
(Launcher.java:225)
    at
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode
(Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main
(Launcher.java:347)
Caused by: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined
method `-' for #<String:0x31a89b54>
Did you mean?  -@
    at RUBY.calc_line_metrics
(uri:classloader:/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/ext/prawn/extensions.rb:330)
    at RUBY.layout_prose
(uri:classloader:/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:2858)
    at RUBY.layout_title_page
(uri:classloader:/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:2724)
    at RUBY.theme_font
(uri:classloader:/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:3789)
    at
uri_3a_classloader_3a_.gems.prawn_minus_2_dot_4_dot_0.lib.prawn.font.font
(uri:classloader:/gems/prawn-2.4.0/lib/prawn/font.rb:60)
    at RUBY.save_font
(uri:classloader:/gems/prawn-2.4.0/lib/prawn/font.rb:214)
    at
uri_3a_classloader_3a_.gems.prawn_minus_2_dot_4_dot_0.lib.prawn.font.font
(uri:classloader:/gems/prawn-2.4.0/lib/prawn/font.rb:58)
    at
uri_3a_classloader_3a_.gems.asciidoctor_minus_pdf_minus_1_dot_6_dot_0.lib.asciidoctor.pdf.ext.prawn.extensions.font
(uri:classloader:/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/ext/prawn/extensions.rb:208)
    at RUBY.theme_font
(uri:classloader:/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:3788)
    at RUBY.layout_title_page
(uri:classloader:/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:2723)
    at RUBY.indent
(uri:classloader:/gems/prawn-2.4.0/lib/prawn/document/bounding_box.rb:297)
    at RUBY.indent
(uri:classloader:/gems/prawn-2.4.0/lib/prawn/document.rb:528)
    at RUBY.layout_title_page
(uri:classloader:/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:2722)
    at RUBY.theme_font
(uri:classloader:/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:3789)
    at RUBY.font
(uri:classloader:/gems/prawn-2.4.0/lib/prawn/font.rb:60)
    at RUBY.save_font
(uri:classloader:/gems/prawn-2.4.0/lib/prawn/font.rb:214)
    at RUBY.font
(uri:classloader:/gems/prawn-2.4.0/lib/prawn/font.rb:58)
    at RUBY.font
(uri:classloader:/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/ext/prawn/extensions.rb:208)
    at RUBY.theme_font
(uri:classloader:/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:3788)
    at RUBY.layout_title_page
(uri:classloader:/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:2658)
    at RUBY.convert_document
(uri:classloader:/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:189)
    at RUBY.convert
(uri:classloader:/gems/asciidoctor-pdf-1.6.0/lib/asciidoctor/pdf/converter.rb:135)
    at RUBY.convert
(uri:classloader:/gems/asciidoctor-2.0.16/lib/asciidoctor/document.rb:948)
    at RUBY.convert
(uri:classloader:/gems/asciidoctor-2.0.16/lib/asciidoctor/convert.rb:118)
    at RUBY.convert_file
(uri:classloader:/gems/asciidoctor-2.0.16/lib/asciidoctor/convert.rb:190)
    at org.jruby.RubyIO.open (org/jruby/RubyIO.java:1148)
    at RUBY.convert_file
(uri:classloader:/gems/asciidoctor-2.0.16/lib/asciidoctor/convert.rb:190)

See
https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.6.0/lib/asciidoctor/pdf/ext/prawn/extensions.rb#L330