HSEARCH-4268 Reduce the amount of transactions created in DatabasePollingAutomaticIndexingEdgeCasesIT#massiveInsert
We mostly care about the amount of inserts per transaction, anyway.

This is to avoid problems with surefire, which apparently fails to
process stdout/stderr when it's too long, and ends up creating a dump file
containing something like this:

```
When writing xml report stdout/stderr
org.apache.maven.surefire.api.report.ReporterException: When writing xml
report stdout/stderr
        at
org.apache.maven.plugin.surefire.report.StatelessXmlReporter.addOutputStreamElement(StatelessXmlReporter.java:508)
        at
org.apache.maven.plugin.surefire.report.StatelessXmlReporter.createOutErrElements(StatelessXmlReporter.java:483)
        at
org.apache.maven.plugin.surefire.report.StatelessXmlReporter.serializeTestClassWithoutRerun(StatelessXmlReporter.java:228)
        at
org.apache.maven.plugin.surefire.report.StatelessXmlReporter.serializeTestClass(StatelessXmlReporter.java:213)
        at
org.apache.maven.plugin.surefire.report.StatelessXmlReporter.testSetCompleted(StatelessXmlReporter.java:152)
        at
org.apache.maven.plugin.surefire.report.StatelessXmlReporter.testSetCompleted(StatelessXmlReporter.java:51)
        at
org.apache.maven.plugin.surefire.report.TestSetRunListener.testSetCompleted(TestSetRunListener.java:193)
        at
org.apache.maven.plugin.surefire.booterclient.output.ForkClient$TestSetCompletedListener.handle(ForkClient.java:139)
        at
org.apache.maven.plugin.surefire.booterclient.output.ForkClient$TestSetCompletedListener.handle(ForkClient.java:128)
        at
org.apache.maven.plugin.surefire.booterclient.output.ForkedProcessEventNotifier.notifyEvent(ForkedProcessEventNotifier.java:232)
        at
org.apache.maven.plugin.surefire.booterclient.output.ForkClient.handleEvent(ForkClient.java:361)
        at
org.apache.maven.plugin.surefire.booterclient.output.ForkClient.handleEvent(ForkClient.java:57)
        at
org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:91)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.FileNotFoundException:
/tmp/stdout3144687467860922848deferred (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at
java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at
java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at
org.apache.maven.surefire.shared.io.output.DeferredFileOutputStream.writeTo(DeferredFileOutputStream.java:321)
        at
org.apache.maven.plugin.surefire.report.Utf8RecodingDeferredFileOutputStream.writeTo(Utf8RecodingDeferredFileOutputStream.java:85)
        at
org.apache.maven.plugin.surefire.report.StatelessXmlReporter.addOutputStreamElement(StatelessXmlReporter.java:502)
        ... 13 more
```